on:
  release:
    types:
      - created

name: Build docker images
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Get current date
      id: get-date
      run: echo "::set-output name=date::$(date +'%Y-%m-%dT%T%z')"

    - name: Get and strip version tag
      id: strip-v
      run: |
          VERSION=${{ github.event.release.tag_name }}
          STRIPPED_VERSION=${VERSION#v}
          echo "::set-output name=version::$STRIPPED_VERSION"

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log into Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/386,linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7
        build-args: |
          VERSION=${{ github.event.release.tag_name }}
          COMMIT=${{ github.sha }}
          BRANCH=master
          DATE=${{ steps.get-date.outputs.date }}
        push: true
        tags: |
          rqlite/rqlite:latest
          rqlite/rqlite:${{ steps.strip-v.outputs.version }}
