name: Build Go Program on Windows

on: push

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'  # Replace with the Go version you need

    - name: Install C Compiler
      run: choco install mingw

    - name: Verify GCC Installation
      run: gcc --version

    - name: Build Go Program
      run:  set CGO_ENABLED=1 && set CC=gcc && go build -a -tags sqlite_omit_load_extension -ldflags="-w -s" ./...
